apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: naglfarcloud-manager-role
  namespace: naglfar-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: naglfarcloud-manager-rolebinding
  namespace: naglfar-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: naglfarcloud-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: naglfar-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: naglfar-labeler
  namespace: naglfar-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - command: ["/manager"]
        args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        image: naglfarcloud-manager:latest
        imagePullPolicy: IfNotPresent
        name: manager        
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: naglfar-labeler-certs
 