apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: labeler-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: naglfar-system/naglfar-label-cert
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: naglfar-labeler-service
        namespace: naglfar-system
        path: /mutate-v1-pod
    failurePolicy: Fail
    name: mpod.kb.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
