kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: naglfar-scheduler
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - events
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - bindings
      - pods/binding
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - "naglfar.pingcap.com"
    resources:
      - podgroups
    verbs:
      - create
      - get
      - list
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: naglfar-scheduler-sa
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: naglfar-scheduler
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: naglfar-scheduler
subjects:
  - kind: ServiceAccount
    name: naglfar-scheduler-sa
    namespace: kube-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    clientConnection:
      kubeconfig: "/etc/kubernetes/scheduler.conf"
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: naglfar-scheduler
      plugins:
        queueSort:
          enabled:
            - name: naglfar-scheduler
          disabled:
            - name: "*"
        preFilter:
          enabled:
            - name: naglfar-scheduler
        permit:
          enabled:
            - name: naglfar-scheduler
        reserve:
          enabled:
            - name: naglfar-scheduler
        postBind:
          enabled:
            - name: naglfar-scheduler
      pluginConfig:
      - name: naglfar-scheduler
        args:
          scheduleTimeout: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naglfar-scheduler
  namespace: kube-system
  labels:
    component: naglfar-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: naglfar-scheduler
  template:
    metadata:
      labels:
        component: naglfar-scheduler
    spec:
      serviceAccount: naglfar-scheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
        - hostPath:
            path: /etc/kubernetes/scheduler.conf
            type: FileOrCreate
          name: kubeconfig
      containers:
        - name: naglfar-scheduler-ctrl
          image: naglfar-scheduler:latest
          imagePullPolicy: IfNotPresent
          args:
            - /bin/kube-scheduler
            - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
            - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --bind-address=127.0.0.1
            - --kubeconfig=/etc/kubernetes/scheduler.conf
            - --leader-elect=false
            - --port=0
            - --v=3
          resources:
            requests:
              cpu: "100m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes/scheduler-config.yaml
              subPath: scheduler-config.yaml
            - name: kubeconfig
              mountPath: /etc/kubernetes/scheduler.conf
              readOnly: true

