apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster1-pd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-scheduler
  template:
    metadata:
      labels:
        app: test-scheduler
      annotations:
        naglfar/podgroup: tidb-cluster-1.pd
    spec:
      schedulerName: naglfar-scheduler
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80