apiVersion: naglfar.pingcap.com/v1
kind: PodGroup
metadata:
  name: tidb-cluster
spec:
  minMember: 3
  scheduleTimeout: 100s
  subGroups:
    pd:
      minMember: 1
    tikv:
      minMember: 1
    tidb:
      minMember: 1
---
# IT IS NOT SUITABLE FOR PRODUCTION USE.
# This YAML describes a basic TiDB cluster with minimum resource requirements,
# which should be able to run in any Kubernetes cluster with storage support.
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: nightly
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  pd:
    annotations:
      naglfar/podgroup: tidb-cluster.pd
    baseImage: pingcap/pd
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    storageClassName: standard
    requests:
      storage: "100Mi"
    config: {}
  tikv:
    annotations:
      naglfar/podgroup: tidb-cluster.tikv
    baseImage: pingcap/tikv
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    storageClassName: standard
    requests:
      storage: "100Mi"
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "0MB"
      rocksdb:
        # In basic examples, we set this to avoid the following error in some Kubernetes clusters:
        # "the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    annotations:
      naglfar/podgroup: tidb-cluster.tidb
    baseImage: pingcap/tidb
    replicas: 1
    service:
      type: ClusterIP
    config: {}
