apiVersion: naglfar.pingcap.com/v1
kind: PodGroup
metadata:
  name: nginx-cluster
spec:
  minMember: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 10
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        naglfar/podgroup: nginx-cluster
    spec:
      terminationGracePeriodSeconds: 10
      schedulerName: naglfar-scheduler
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi